server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://47.103.218.171:3306/oomall2?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 741120ab
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  typeAliasesPackage: xmu.oomall.order.domain
  configuration:
    map-underscore-to-camel-case: true



